local HomeService = {}
HomeService.__index = HomeService

local Workspace = game:GetService("Workspace")

local HomeCfg = require(script.Parent:WaitForChild("HomeCfg"))
local StationService = require(script.Parent:WaitForChild("StationService"))

local function getHouseNumber(house)
	local suffix = house.Name:match("(%d+)$")
	return suffix and tonumber(suffix) or nil
end

local function sortByHouseNumber(a, b)
	local aNumber = getHouseNumber(a)
	local bNumber = getHouseNumber(b)

	if aNumber and bNumber and aNumber ~= bNumber then
		return aNumber < bNumber
	end

	if aNumber and not bNumber then
		return true
	end

	if bNumber and not aNumber then
		return false
	end

	return a.Name < b.Name
end

local function getOrCreateFolder(parent, name)
	local folder = parent:FindFirstChild(name)

	if folder then
		if folder:IsA("Folder") then
			return folder
		end

		warn("[Homestead]", parent:GetFullName(), "tiene", name, "pero no es Folder.")
		return nil
	end

	folder = Instance.new("Folder")
	folder.Name = name
	folder.Parent = parent

	return folder
end

local function getOptionalFolder(parent, name)
	if not parent or not name then
		return nil
	end

	local folder = parent:FindFirstChild(name)
	if not folder then
		return nil
	end

	if folder:IsA("Folder") then
		return folder
	end

	warn("[Homestead]", parent:GetFullName(), "tiene", name, "pero no es Folder.")
	return nil
end

local function setLogicalPartProperties(part)
	part.Anchored = true
	part.CanCollide = false
	part.CanTouch = false
	part.CanQuery = false
	part.Transparency = 1
end

local function getOrCreateLogicalPart(parent, name, cframe, size)
	local part = parent:FindFirstChild(name)
	local created = false

	if part then
		if not part:IsA("BasePart") then
			warn("[Homestead]", parent:GetFullName(), "tiene", name, "pero no es BasePart.")
			return nil
		end
	else
		part = Instance.new("Part")
		part.Name = name
		created = true

		if cframe then
			part.CFrame = cframe
		end

		if size then
			part.Size = size
		end

		part:SetAttribute("AutoGenerated", true)
		part.Parent = parent
	end

	setLogicalPartProperties(part)
	return part
end

local function validateExistingLogicalPart(parent, name)
	if not parent or not name then
		return nil
	end

	local part = parent:FindFirstChild(name)
	if not part then
		return nil
	end

	if not part:IsA("BasePart") then
		warn("[Homestead]", parent:GetFullName(), "tiene", name, "pero no es BasePart.")
		return nil
	end

	setLogicalPartProperties(part)
	return part
end

local function getHouseCenter(house)
	local corralCenter = house:FindFirstChild("CorralCenter")
	if corralCenter and corralCenter:IsA("BasePart") then
		return corralCenter.Position
	end

	if house:IsA("Model") then
		return house:GetPivot().Position
	end

	local total = Vector3.zero
	local count = 0

	for _, desc in ipairs(house:GetDescendants()) do
		if desc:IsA("BasePart") then
			total += desc.Position
			count += 1
		end
	end

	if count > 0 then
		return total / count
	end

	return Vector3.zero
end

function HomeService.new()
	local self = setmetatable({}, HomeService)

	self.HousesFolder = Workspace:WaitForChild(HomeCfg.Names.Houses)
	self.Runtime = Workspace:FindFirstChild(HomeCfg.Names.HomeRuntime)

	if not self.Runtime then
		self.Runtime = Instance.new("Folder")
		self.Runtime.Name = HomeCfg.Names.HomeRuntime
		self.Runtime.Parent = Workspace
	end

	self.StationService = StationService.new()
	self.PlayerHomes = {}

	self:ScanHouses()

	return self
end

function HomeService:EnsureAnimalFolders(house)
	local animalSpawns = getOrCreateFolder(house, HomeCfg.Names.AnimalSpawns)
	local chickenSpawns = animalSpawns and getOrCreateFolder(animalSpawns, HomeCfg.Names.ChickenSpawns)
	local cuySpawns = animalSpawns and getOptionalFolder(animalSpawns, HomeCfg.Names.CuySpawns)
	local animalZones = getOrCreateFolder(house, HomeCfg.Names.AnimalZones)

	return animalSpawns, chickenSpawns, cuySpawns, animalZones
end

function HomeService:EnsureChickenSpawns(house, chickenSpawns)
	if not chickenSpawns then
		return
	end

	local center = getHouseCenter(house)
	local offsets = {
		Vector3.new(-4, 0, 1),
		Vector3.new(0, 0, 0),
		Vector3.new(4, 0, 1),
	}

	local count = HomeCfg.Animals.Chicken.Count or 3
	for index = 1, count do
		local offset = offsets[index] or Vector3.new((index - 2) * 4, 0, 1)
		local name = string.format("Spawn%02d", index)
		getOrCreateLogicalPart(chickenSpawns, name, CFrame.new(center + offset), Vector3.new(1, 1, 1))
	end

	for _, obj in ipairs(chickenSpawns:GetChildren()) do
		if obj:IsA("BasePart") then
			setLogicalPartProperties(obj)
		end
	end
end

function HomeService:EnsureCuySpawns(house, cuySpawns)
	if not cuySpawns then
		warn(string.format("[Homestead] %s no tiene CuySpawns; no se crearÃ¡n cuys.", house.Name))
		return
	end

	local validSpawns = 0
	for _, obj in ipairs(cuySpawns:GetChildren()) do
		if obj:IsA("BasePart") then
			validSpawns += 1
			setLogicalPartProperties(obj)
		end
	end

	if validSpawns == 0 then
		warn(string.format("[Homestead] %s tiene CuySpawns sin partes Spawn; no se crearÃ¡n cuys.", house.Name))
	end
end

function HomeService:EnsureAnimalZones(house, animalZones)
	if not animalZones then
		return
	end

	local center = getHouseCenter(house)
	local roamZone = getOrCreateLogicalPart(
		animalZones,
		HomeCfg.Names.ChickenRoamZone,
		CFrame.new(center),
		Vector3.new(34, 1, 34)
	)

	local coopZone = getOrCreateLogicalPart(
		animalZones,
		HomeCfg.Names.ChickenCoopZone,
		CFrame.new(center + Vector3.new(0, 0, 8)),
		Vector3.new(10, 1, 8)
	)

	validateExistingLogicalPart(animalZones, HomeCfg.Names.ChickenIndoorZone)
	validateExistingLogicalPart(animalZones, HomeCfg.Names.CuyIndoorZone)

	local eggPoints = getOrCreateFolder(animalZones, HomeCfg.Names.ChickenEggPoints)
	if not eggPoints then
		return
	end

	local eggBase = (coopZone and coopZone.Position) or (roamZone and roamZone.Position) or center
	local offsets = {
		Vector3.new(-2, 0.25, 0),
		Vector3.new(0, 0.25, 0),
		Vector3.new(2, 0.25, 0),
	}

	for index = 1, 3 do
		local name = string.format("EggPoint%02d", index)
		getOrCreateLogicalPart(eggPoints, name, CFrame.new(eggBase + offsets[index]), Vector3.new(1, 1, 1))
	end

	for _, obj in ipairs(eggPoints:GetChildren()) do
		if obj:IsA("BasePart") then
			setLogicalPartProperties(obj)
		end
	end

	if not validateExistingLogicalPart(animalZones, HomeCfg.Names.CuyRoamZone) then
		warn(string.format("[Homestead] %s no tiene CuyRoamZone manual.", house.Name))
	end

	local hidePoints = getOptionalFolder(animalZones, HomeCfg.Names.CuyHidePoints)
	if not hidePoints then
		warn(string.format("[Homestead] %s no tiene CuyHidePoints manual.", house.Name))
		return
	end

	local validHidePoints = 0
	for _, obj in ipairs(hidePoints:GetChildren()) do
		if obj:IsA("BasePart") then
			validHidePoints += 1
			setLogicalPartProperties(obj)
		end
	end

	if validHidePoints == 0 then
		warn(string.format("[Homestead] %s tiene CuyHidePoints sin HidePoint manual.", house.Name))
	end
end

function HomeService:EnsureHouseSetup(house, fallbackIndex)
	local houseNumber = getHouseNumber(house)
	house:SetAttribute("HouseId", houseNumber or fallbackIndex)

	if house:GetAttribute("OwnerId") == nil then
		house:SetAttribute("OwnerId", 0)
	end

	if house:GetAttribute("Taken") == nil then
		house:SetAttribute("Taken", false)
	end

	self.StationService:EnsureStations(house)

	local _, chickenSpawns, cuySpawns, animalZones = self:EnsureAnimalFolders(house)
	self:EnsureChickenSpawns(house, chickenSpawns)
	self:EnsureCuySpawns(house, cuySpawns)
	self:EnsureAnimalZones(house, animalZones)
end

function HomeService:ScanHouses()
	local houses = {}

	for _, house in ipairs(self.HousesFolder:GetChildren()) do
		if house:IsA("Model") or house:IsA("Folder") then
			table.insert(houses, house)
		end
	end

	table.sort(houses, sortByHouseNumber)

	for index, house in ipairs(houses) do
		self:EnsureHouseSetup(house, index)
	end

	if HomeCfg.Debug.PrintStartup then
		print("[Homestead] Casas preparadas:", #houses)
	end
end

function HomeService:GetHouseByOwner(player)
	for _, house in ipairs(self.HousesFolder:GetChildren()) do
		if house:IsA("Model") or house:IsA("Folder") then
			if house:GetAttribute("Taken") == true and house:GetAttribute("OwnerId") == player.UserId then
				return house
			end
		end
	end

	return nil
end

function HomeService:GetOrCreateRuntimeFolder(player)
	local folderName = "Home_" .. player.UserId
	local folder = self.Runtime:FindFirstChild(folderName)

	if not folder then
		folder = Instance.new("Folder")
		folder.Name = folderName
		folder.Parent = self.Runtime
		folder:SetAttribute("OwnerId", player.UserId)
		folder:SetAttribute("OwnerName", player.Name)
	end

	return folder
end

function HomeService:RefreshPlayerHome(player)
	local house = self:GetHouseByOwner(player)

	if not house then
		self.PlayerHomes[player.UserId] = nil

		local oldFolder = self.Runtime:FindFirstChild("Home_" .. player.UserId)
		if oldFolder then
			oldFolder:Destroy()
		end

		return nil
	end

	local runtimeFolder = self:GetOrCreateRuntimeFolder(player)

	local data = {
		Player = player,
		House = house,
		RuntimeFolder = runtimeFolder,
		HouseId = house:GetAttribute("HouseId") or 0,
		Stations = self.StationService:GetStationSummary(house),
	}

	self.PlayerHomes[player.UserId] = data

	runtimeFolder:SetAttribute("HouseName", house.Name)
	runtimeFolder:SetAttribute("HouseId", data.HouseId)

	return data
end

function HomeService:GetHomeInfo(player)
	local data = self:RefreshPlayerHome(player)

	if not data then
		return {
			HasHome = false,
			Message = "No tienes casa reclamada todavÃ­a.",
		}
	end

	local animalsFolder = data.RuntimeFolder:FindFirstChild("Animals")
	local chickenFolder = animalsFolder and animalsFolder:FindFirstChild("Chickens")
	local cuyFolder = animalsFolder and animalsFolder:FindFirstChild("Cuys")
	local eggFolder = animalsFolder and animalsFolder:FindFirstChild("Eggs")

	local chickenCount = chickenFolder and #chickenFolder:GetChildren() or 0
	local cuyCount = cuyFolder and #cuyFolder:GetChildren() or 0
	local eggCount = eggFolder and #eggFolder:GetChildren() or 0

	return {
		HasHome = true,
		HouseName = data.House.Name,
		HouseId = data.HouseId,
		Stations = data.Stations,
		ChickenCount = chickenCount,
		CuyCount = cuyCount,
		EggCount = eggCount,
		Message = "CabaÃ±a detectada correctamente.",
	}
end

function HomeService:Release(player)
	self.PlayerHomes[player.UserId] = nil

	local folder = self.Runtime:FindFirstChild("Home_" .. player.UserId)
	if folder then
		folder:Destroy()
	end
end

return HomeService
