local Workspace = game:GetService("Workspace")

local HomesteadAnimalPlacement = {}

HomesteadAnimalPlacement.TestVisiblePlacement = true

local TEST_OFFSETS = {
	Chicken = {
		Vector3.new(-6, 0, 7),
		Vector3.new(0, 0, 9),
		Vector3.new(6, 0, 7),
	},
	Cuy = {
		Vector3.new(-4, 0, -7),
		Vector3.new(4, 0, -7),
	},
}

local function getHouseCenter(house)
	local corralCenter = house and house:FindFirstChild("CorralCenter")
	if corralCenter and corralCenter:IsA("BasePart") then
		return corralCenter.Position
	end

	if house and house:IsA("Model") then
		return house:GetPivot().Position
	end

	if house then
		local total = Vector3.zero
		local count = 0
		for _, desc in ipairs(house:GetDescendants()) do
			if desc:IsA("BasePart") and desc.Transparency < 1 then
				total += desc.Position
				count += 1
			end
		end
		if count > 0 then
			return total / count
		end
	end

	return Vector3.zero
end

local function makeGroundParams(house)
	local filter = {}
	if house then
		table.insert(filter, house)
	end
	for _, folderName in ipairs({ "HomeRuntime", "SheepRuntime", "PredatorRuntime", "MythicResourceRuntime" }) do
		local folder = Workspace:FindFirstChild(folderName)
		if folder then
			table.insert(filter, folder)
		end
	end

	local params = RaycastParams.new()
	params.FilterType = Enum.RaycastFilterType.Exclude
	params.FilterDescendantsInstances = filter
	params.IgnoreWater = false
	return params
end

function HomesteadAnimalPlacement.ProjectToGround(position, house)
	local params = makeGroundParams(house)
	local origin = Vector3.new(position.X, position.Y + 80, position.Z)
	local result = Workspace:Raycast(origin, Vector3.new(0, -180, 0), params)
	if result and result.Normal.Y > 0.35 then
		return Vector3.new(position.X, result.Position.Y + 0.5, position.Z), result
	end
	return position, nil
end

local function setMarkerProperties(part)
	part.Anchored = true
	part.CanCollide = false
	part.CanTouch = false
	part.CanQuery = false
	part.Transparency = 1
end

local function ensureFolder(parent, name)
	local folder = parent:FindFirstChild(name)
	if folder then
		return folder:IsA("Folder") and folder or nil
	end
	folder = Instance.new("Folder")
	folder.Name = name
	folder.Parent = parent
	return folder
end

local function ensureTestMarker(folder, name, worldPosition, house)
	local marker = folder:FindFirstChild(name)
	if not marker then
		marker = Instance.new("Part")
		marker.Name = name
		marker.Size = Vector3.new(1, 1, 1)
		marker:SetAttribute("AutoGenerated", true)
		marker.Parent = folder
	end
	if not marker:IsA("BasePart") then
		return nil
	end

	local grounded = HomesteadAnimalPlacement.ProjectToGround(worldPosition, house)
	marker.CFrame = CFrame.new(grounded)
	setMarkerProperties(marker)
	marker:SetAttribute("AnimalVisibilityTestMarker", true)
	return marker
end

local function syncSpeciesMarkers(house, animalSpawns, folderName, speciesId, count)
	local folder = ensureFolder(animalSpawns, folderName)
	if not folder then
		return 0
	end

	local center = getHouseCenter(house)
	local offsets = TEST_OFFSETS[speciesId]
	local placed = 0
	for index = 1, count do
		local offset = offsets[index] or Vector3.new((index - 1) * 3, 0, 0)
		local marker = ensureTestMarker(folder, string.format("Spawn%02d", index), center + offset, house)
		if marker then
			placed += 1
		end
	end
	return placed
end

local function syncCuyRoamZone(house, animalZones, zoneName)
	if not animalZones or not zoneName then
		return nil
	end
	local zone = animalZones:FindFirstChild(zoneName)
	if not zone then
		zone = Instance.new("Part")
		zone.Name = zoneName
		zone.Size = Vector3.new(22, 1, 18)
		zone:SetAttribute("AutoGenerated", true)
		zone.Parent = animalZones
	end
	if not zone:IsA("BasePart") then
		return nil
	end

	local center = getHouseCenter(house) + Vector3.new(0, 0, -6)
	local grounded = HomesteadAnimalPlacement.ProjectToGround(center, house)
	zone.CFrame = CFrame.new(grounded)
	zone.Size = Vector3.new(22, 1, 18)
	setMarkerProperties(zone)
	zone:SetAttribute("AnimalVisibilityTestMarker", true)
	return zone
end

function HomesteadAnimalPlacement.SyncHouse(house, homeCfg)
	if not HomesteadAnimalPlacement.TestVisiblePlacement or not house or not homeCfg then
		return nil
	end

	local animalSpawns = ensureFolder(house, homeCfg.Names.AnimalSpawns)
	local animalZones = ensureFolder(house, homeCfg.Names.AnimalZones)
	if not animalSpawns or not animalZones then
		return nil
	end

	local chickenCount = math.max(1, tonumber(homeCfg.Animals.Chicken.Count) or 3)
	local cuyCount = math.max(1, tonumber(homeCfg.Animals.Cuy.Count) or 2)
	local chickens = syncSpeciesMarkers(house, animalSpawns, homeCfg.Names.ChickenSpawns, "Chicken", chickenCount)
	local cuys = syncSpeciesMarkers(house, animalSpawns, homeCfg.Names.CuySpawns, "Cuy", cuyCount)
	syncCuyRoamZone(house, animalZones, homeCfg.Names.CuyRoamZone)

	house:SetAttribute("AnimalVisibilityTestPlacement", true)
	house:SetAttribute("AnimalVisibilityChickenMarkers", chickens)
	house:SetAttribute("AnimalVisibilityCuyMarkers", cuys)

	return {
		ChickenMarkers = chickens,
		CuyMarkers = cuys,
	}
end

return HomesteadAnimalPlacement
